version: '3'
services:
  app:
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - URL=${URL}
      - PASSWORD=${POSTGRES_PASSWORD}
      - USERNAME=${POSTGRES_USER}
      - changeLogFile=db/changelog/db.changelog-master.xml
      - spring.liquibase.url=${URL}
      - spring.liquibase.user=${POSTGRES_USER}
      - spring.liquibase.password=${POSTGRES_PASSWORD}
      - spring.liquibase.change-log=db/changelog/db.changelog-master.xml
    env_file:
      - .env
    volumes:
      - ./:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
